version: '1.0'

services:
  database:
    container_name: "mysql-db"
    image: mysql:8.2.0
    #    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "kotlin-restful-api"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
  app:
    container_name: "kotlin-app"
    image: kotlin-restful-api:0.0.1
#    restart: always
    ports:
      - 8080:8080
    environment:
      DB_UNAME: "user"
      DB_PASS: "password"
      DB_URL: "jdbc:mysql://mysql-db:3306/kotlin-restful-api"